config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chats/index'
  get 'chats/show'
  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'
  mount ActionCable.server => "/cable"

  delete "posts/purge_image/:id", to: "posts#purge_image", as: "purge_post_image"
  resources :posts do
    resources :comments, only: [:create]
  end

  resources :users, only: [:index]
  post "users/:cur_id/follow/:id/:flag", to: "users#follow", as: "follow_user"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "posts#index", as: :authenticated_user_root
      get "users/:id", to: "users#show", as: "show_user"
    end
    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_user_root
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check

  namespace 'api' do
    namespace 'v1' do
      resources :posts, only: [:index, :show, :update, :destroy]
      delete "purge_image/:id", to: "posts#purge_image"
      post 'chats/:id', to: 'chats#update_users'
      post 'users/:user_id/chats/:id', to: 'messages#create'
      resources :chats, only: [:show]
      resources :users, only: [:index, :show] do
        resources :chats, only: [:index, :create]
        resources :posts, only: [:create] do
          resources :comments, only: [:create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :last_vieweds
  has_many :chats, through: :last_vieweds

  before_create :default_following_ids
  def default_following_ids
    self.following_ids = []
  end
end

app/controllers/api/v1/users_controller.rb
include ActionView::Helpers::DateHelper

module Api
  module V1
    class UsersController < ApplicationController
      def index
        users = User.all
        render json: users, status: :ok
      end

      def show
        user = User.find(params[:id])
        user_json = user.as_json
        ordered = user.posts.order(created_at: :desc)
        posts_json = ordered.as_json
        for i in 0..posts_json.length - 1 do
          images = ordered[i].images.map do |img|
            {
              id: img.id,
              url: url_for(img),
            }
          end
          posts_json[i].merge!(name: User.find(ordered[i].user_id).name)
          posts_json[i].merge!(time: time_ago_in_words(ordered[i].created_at))
          posts_json[i].merge!(images: images)
        end
        
        user_json.merge!(posts: posts_json)
        render json: user_json, status: :ok
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def follow
    user = User.find(params[:cur_id])
    if (params[:flag] == "true")
      user.following_ids.push(params[:id].to_i)
    else
      user.following_ids.delete(params[:id].to_i)
    end
    user.save!
    respond_to do |format|
      format.html { redirect_to "/" }
      format.json { render json: user.following_ids }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<a class="user-card row" href="/users/<%= user.id %>">
  <%= render "layouts/ava", locals: {class: "user-card__ava", id: user.id} %>
  <h3 class="user-card__name">
    <%= user.name %>
  </h3>
</a>

app/views/users/index.html.erb
<section class="section">
  <%= render @users %>
</section>

app/views/users/show.html.erb
<section class="section">
  <%= render @user %>

  <div class="row">
    <% if current_user %>
      <% if current_user.id == params[:id].to_i %>
        <%= link_to "Пост", new_post_path, class: "btn" %>
      <% elsif current_user.following_ids.include? params[:id].to_i %>
        <%= button_to "Отписаться", follow_user_path(cur_id: current_user.id, id: params[:id], flag: "false"),
          method: :post, class: "btn btn_red" %>
      <% else %>
        <%= button_to "Подписаться", follow_user_path(cur_id: current_user.id, id: params[:id], flag: "true"),
          method: :post, class: "btn" %>
      <% end %>
    <% end %>
  </div>
  
  <%= render partial: "posts/post", collection: @user.posts.order(created_at: :desc) %>
</section>