config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chats/index'
  get 'chats/show'
  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'
  mount ActionCable.server => "/cable"

  delete "posts/purge_image/:id", to: "posts#purge_image", as: "purge_post_image"
  resources :posts do
    resources :comments, only: [:create]
  end

  resources :users, only: [:index]
  post "users/:cur_id/follow/:id/:flag", to: "users#follow", as: "follow_user"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "posts#index", as: :authenticated_user_root
      get "users/:id", to: "users#show", as: "show_user"
    end
    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_user_root
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check

  namespace 'api' do
    namespace 'v1' do
      resources :posts, only: [:index, :show, :update, :destroy]
      delete "purge_image/:id", to: "posts#purge_image"
      post 'chats/:id', to: 'chats#update_users'
      post 'users/:user_id/chats/:id', to: 'messages#create'
      resources :chats, only: [:show]
      resources :users, only: [:index, :show] do
        resources :chats, only: [:index, :create]
        resources :posts, only: [:create] do
          resources :comments, only: [:create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments
end

app/controllers/api/v1/posts_controller.rb
include ActionView::Helpers::DateHelper

module Api
  module V1
    class PostsController < ApplicationController
      def index
        posts = Post.order(created_at: :desc)
        posts_json = posts.as_json

        for i in 0...posts_json.length do
          images = posts[i].images.map do |img|
            {
              id: img.id,
              url: url_for(img),
            }
          end
          posts_json[i].merge!(name: User.find(posts[i].user_id).name)
          posts_json[i].merge!(time: time_ago_in_words(posts[i].created_at))
          posts_json[i].merge!(images: images)
        end
        render json: posts_json, status: :ok
      end

      def show
        post = Post.find(params[:id])
        post_json = post.as_json
        images = post.images.map do |img|
          {
            id: img.id,
            url: url_for(img),
          }
        end

        ordered = post.comments.order(created_at: :desc)
        comments_json = ordered.as_json
        for i in 0..comments_json.length - 1
          comments_json[i].merge!(name: User.find(ordered[i].user_id).name)
          comments_json[i].merge!(time: time_ago_in_words(ordered[i].created_at))
        end

        post_json.merge!(name: User.find(post.user_id).name)
        post_json.merge!(time: time_ago_in_words(post.created_at))
        post_json.merge!(images: images)
        post_json.merge!(comments: comments_json)
        render json: post_json, status: :ok
      end

      def create
        user = User.find(params[:user_id])
        post = user.posts.create(body: params[:body])
        post.images.attach(params[:images])
        render json: post, status: :created
      end

      def update
        post = Post.find(params[:id])
        if post.update(body: params[:body])
          post.images.attach(params[:images])
          render json: post, status: :ok
        else
          render json: {}, status: :unprocessible_entity
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.comments.destroy_all
        post.destroy
        render json: {message: "Deleted posts/#{params[:id]}"}, status: :no_content
      end

      def purge_image
        image = ActiveStorage::Attachment.find(params[:id])
        image.purge
        render json: {message: "Deleted image #{params[:id]}"}, status: :no_content
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:q].present?
      @posts = Post.where("body like ?", "%#{params[:q]}%")
    else
      @posts = Post.where(user_id: current_user.following_ids)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.create(params.require(:post).permit(:body))
    post.images.attach(params[:post][:images])
    redirect_to post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:body))
      @post.images.attach(params[:post][:images])
      redirect_to @post
    else
      render :edit, status: :unprocessible_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to "/"
  end

  def purge_image
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge
    redirect_back fallback_location: "/"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="post">
  <%= render "layouts/autor", locals: {id: comment.user.id, name: comment.user.name, time: comment.created_at} %>
  <p>
    <%= comment.body %>
  </p>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, class: "section" do |form| %>
  <fieldset>
    <%= form.text_area :body, class: "input" %>
  </fieldset>
  <%= yield %>
  <fieldset>
    <%= form.file_field :images, multiple: true %>
  </fieldset>
  
  <%= form.button "Готово", class: "btn" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post" data-controller="slider">
  <div class="post__slider slider hide" data-slider-target="slider">
    <button class="slider__close" data-action="click->slider#close">X</button>
    <button class="slider__btn" data-action="click->slider#prev"></button>
    <button class="slider__btn" data-action="click->slider#next"></button>
    <img src="" alt="SliderImage" data-slider-target="img">
  </div>
  <%= render "layouts/autor", locals: {id: post.user.id, name: post.user.name, time: post.created_at} %>
  <a class="post__body" href="/posts/<%= post.id %>">
    <%= post.body %>
  </a>
  <div class="post__imgs">
    <% post.images.each_with_index do |image, i| %>
      <figure class="post__img" data-action="click->slider#open" data-slider-i-param="<%= i %>"><%= image_tag image, data: {slider_target: "slide"} %></figure>
    <% end %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<% if current_user && current_user.id == @post.user_id %>
  <%= render layout: "form" do %>
    <div class="post__imgs">
      <% @post.images.each do |image| %>
        <figure class="post__img"><%= image_tag(image) %></figure>
        <%= link_to "Удалить", purge_post_image_path(image), data: { turbo_method: :delete }, class: "btn btn_red" %>
      <% end %>
    </div>
  <% end %>
  <%= link_to "Удалить", @post, data: { turbo_method: :delete }, class: "del-btn btn btn_red" %>
<% else %>
  <p>Вы не являетесь создателем</p>
  <%= link_to "Назад", url_for(:back), class: "btn" %>
<% end %>

app/views/posts/index.html.erb
<section class="section">
  <div class="row">
    <% if current_user %>
      <%= link_to "Пост", new_post_path, class: "btn" %>
    <% end %>
    <%= form_with url: posts_path, method: :get, class: "row" do |form| %>
      <%= form.search_field :q, class: "input", placeholder: "Поиск постов..." %>
      <%= form.submit "Искать", class: "btn" %>
    <% end %>
  </div>
  
  <%= render @posts.order(created_at: :desc) %>
</section>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<section class="section">
  <%= render @post %>

  <%= form_with model: [@post, @post.comments.build] do |form| %>
    <%= form.text_area :body, class: "input", placeholder: "Комментарий..." %>
    <div class="row">
      <%= form.submit "Отправить", class: "btn" %>
      <%= link_to "Редактировать пост", edit_post_path, class: "btn" %>
    </div>
  <% end %>

  <%= render partial: "comment", collection: @post.comments.order(created_at: :desc) %>
</section>