config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  get 'chats/index'
  get 'chats/show'
  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'
  mount ActionCable.server => "/cable"

  delete "posts/purge_image/:id", to: "posts#purge_image", as: "purge_post_image"
  resources :posts do
    resources :comments, only: [:create]
  end

  resources :users, only: [:index]
  post "users/:cur_id/follow/:id/:flag", to: "users#follow", as: "follow_user"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "posts#index", as: :authenticated_user_root
      get "users/:id", to: "users#show", as: "show_user"
    end
    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_user_root
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check

  namespace 'api' do
    namespace 'v1' do
      resources :posts, only: [:index, :show, :update, :destroy]
      delete "purge_image/:id", to: "posts#purge_image"
      post 'chats/:id', to: 'chats#update_users'
      post 'users/:user_id/chats/:id', to: 'messages#create'
      resources :chats, only: [:show]
      resources :users, only: [:index, :show] do
        resources :chats, only: [:index, :create]
        resources :posts, only: [:create] do
          resources :comments, only: [:create]
        end
      end
    end
  end
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_autor.html.erb
<a class="row" href="/users/<%= locals[:id] %>">
  <%= render "layouts/ava", locals: {class: "ava", id: locals[:id]} %>
  <h4><%= locals[:name] %></h4>
  <time class="post__time"><%= time_ago_in_words(locals[:time]) %></time>
</a>

app/views/layouts/_ava.html.erb
<figure class="<%= locals[:class] %>">
  <img class="ava__img" src="/assets/<%= locals[:id] %>.webp" alt="Ava">
</figure>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if current_user %>
    <nav class="footer__container row row_spaced">
      <%= link_to "Посты", "/" %>
      <%= link_to "Профиль", show_user_path(current_user) %>
      <%= link_to "Люди", users_path %>
    </nav>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <% if current_user %>
    <div class="header__container row row_spaced">
      <%= render "layouts/ava", locals: {class: "ava", id: current_user.id} %>
      <%= link_to "Выйти", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn_red" %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/header" %>
      <main class="main">
        <div class="main__container">
          <%= render "layouts/alerts" %>
          <%= yield %>
        </div>
      </main>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>